Week 5 - R Quiz
========================================================

Question 1
--------------------
```{r}
A <- matrix(c(1,-1,-1,-1), nrow=2)
A
B <- matrix(c(2,-1,3,-2), nrow=2)
B
C <- matrix(c(1,0,0,0), nrow=2)
C
D <- matrix(c(0,1,0,1,0,0,0,0,1), nrow=3)
D
E <- matrix(c(1,0,0,0,0,1,0,1,0), nrow=3)
E

```

Question 2
--------------------

An idempotent matrix is a matrix which, when multiplied by itself, yields itself. Therefore, only matrix C is idempotent as demonstrated below:


```{r}
A %*% A # Not idempotent
B %*% B # Not idempotent
C %*% C # Idempotent
D %*% D # Not idempotent
E %*% E # Not idempotent
```


Question 3
--------------------

A matrix is orthogonal if its transpose is equal to its inverse. Therefore, matrices D & E are orthogonal as demonstrated below:

```{r}
t(A) # Not orthogonal
solve(A)
t(B) # Not orthogonal
solve(B)
t(C) # Not orthogonal (C is a singular matrix so it does not have an inverse)
solve(C)
t(D) # Orthogonal
solve(D)
t(E) # Orthogonal
solve(E)
```

Question 4
--------------------

```{r}
q4vect1 <- c("John Smith","Bob Benson","Todd McLean") #Vector for dataframe
q4vect1
q4vect2 <- c(33,55,88) #Vector for dataframe
q4vect2
q4vect3 <- 4:8 #Vector for final list
q4vect3
q4mtrx <- matrix(c(5,-17,-21,4), nrow=2) #Matrix for final list
q4mtrx
q4arr <- array(1:15, dim = c(5,3,3)) #Array for final list
q4arr
q4dataf <- data.frame(Name = q4vect1, Age = q4vect2) #Dataframe for final list
q4dataf
q4lst <- list(4, "fore", 2, "too", 8, "ate") #List for final list
q4lst
q4finallst <- list(q4vect3,q4mtrx,q4arr,q4dataf,q4lst) #Final list
q4finallst
```
